---
- name: Validate default user
  mysql_user:
    name: "{{ mysql_user_name }}"
    host: 'localhost'
    password: "{{ mysql_user_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  when: mysql_user_name != mysql_root_username

- name: Setup user my.cnf file
  template:
    src: user-my.cnf.j2
    dest: "{{ mysql_user_home }}/.my.cnf"
    owner: "{{ mysql_user_name }}"
    group: "{{ mysql_user_name }}"
    mode: 0600
  when: mysql_user_name != mysql_root_username

- name: Disable root login
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Update MySQL root password for localhost root account
  mysql_user:
    login_user: "{{ mysql_root_username }}"
    user: "{{ mysql_root_username }}"
    password: "{{ mysql_root_password }}"
    host_all: yes
    state: present

- name: Setup root my.cnf file
  template: 
    src: root-my.cnf.j2
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: "{{ mysql_root_username }}"
    group: "{{ mysql_root_username }}"
    mode: 0600

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Drop unused databases
  mysql_db:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ mysql_unused_databases }}"